spring.application.name=EUDRWebApp

# H2 Database Configuration
spring.datasource.url=jdbc:h2:file:./data/testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=user
spring.datasource.password=pass
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.globally_quoted_identifiers=true

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=e8634a66eac166
spring.mail.password=fe943f149a1c2e
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.from=your-email@example.com


